# Generated by Django 5.0.6 on 2024-05-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=50, verbose_name='lstname')),
                ('firstname', models.CharField(max_length=50, verbose_name='firstname')),
                ('patronymic', models.CharField(max_length=50, verbose_name='patronymic')),
                ('login', models.CharField(max_length=100, verbose_name='login')),
                ('password', models.CharField(max_length=100, verbose_name='password')),
                ('mail', models.CharField(max_length=100, verbose_name='password')),
            ],
        ),
    ]
